Первая β-версия
lardc/hw-CSControlBoard pull request #3
Opened 2021-09-07 08:10 UTC by eugene-frost

2021-09-09 09:51 UTC, asytyi requested changes
Ещё у меня компилятор ругается на выражения в функции `SM_SpeedToCycles` что они переполняются, поэтому надо хотя бы для этих переменных в числителе и знаменателе явно указать, что они достаточно длинные)
```
// Stepper motors system config
#define SM_FULL_ROUND_STEPS		200ul	// steps/round
#define SM_MOVING_RER_ROUND		5000ul	// in um/round
```

2021-09-09 09:51 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +Int16U CONTROL_DevicePosition(DevTypeId)
Тип параметра всё же лучше указать

2021-09-09 09:51 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +			break;
Магических чисел в коде быть не должно. Коды корпусов прибора надо или задефайнить, или лучше заенамить.
Например `CaseCode_A2` и т.д.
А сами высоты подтягивать из сохраняемых регистров (можно прямо с нулевого заюзать), чтобы в ходе пусконаладки или доработки адаптера не надо было перекомпилировать проект

2021-09-09 09:51 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +	if (NewState == DS_Clamping || NewState == DS_Sliding)
В прессах для таблеточных приборов слово Sliding использовалось для выкатной системы, которая выдвигалась и задвигалась в рабочую область пресса, чтобы оператор на вытянутых руках не ставил тяжёлый прибор.
Думаю, что для избежания разночтений при работе с разными прошивками лучше это слово заменить. Clamp, Unclamp(?), Release — можно использовать для операций зажатия/разжатия. Move, MoveUp, MoveDown, Positioning — для операций перемещения

2021-09-09 09:51 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +					if (SM_GoToPosition(DataTable[REG_CUSTOM_POS]*1000, DataTable[REG_MAX_SPEED]*1000, 0, 0))
Не уверен, что произведение автоматически кастанётся в инт32. Лучше где-то добавить явное преобразование:
`(Int32U)DataTable[REG_CUSTOM_POS]*1000` или `DataTable[REG_CUSTOM_POS]*1000ul`
чтобы потом не было сюрпризов.

Предлагаю сделать обёртку для функции `SM_GoToPosition`, например `SM_GoToPositionFromReg`. В качестве аргументов передавать значения регистров, а уже в обёртке умножать их на 1000. Запись будет компактнее.

2021-09-21 12:28 UTC, eugene-frost commented
@asytyi Напиши ещё плиз, какая структура DT должна быть? DT в проекте был размером 300 с увеличенными областями NV WR WP, но Constraints под DT был как на 020. Сейчас сделал какой-то гибрид - всё как на 020 (т.к. говорили о совместимости регистров 004 и 020), но размер оставил 300.

2021-10-06 13:25 UTC, asytyi approved these changes
Добро, замечаний не имею

2021-10-06 13:25 UTC, merged