Develop pc bv2.0 mme301
lardc/hw-CSControlBoard pull request #6
Opened 2023-10-24 10:34 UTC by IvanovDmtr

2023-10-30 12:17 UTC, asytyi requested changes

2023-10-30 12:17 UTC, asytyi commented on Firmware/Sources/Controller/Controller.c
> +			break;
В текущей реализации ПО ВУ опрашивает только регистры 96 и 99 в ЗУ. Для опроса регистра Problem надо так же вводить регистр OP_RESULT, чтобы логика билась с логикой других блоков. Или делать патч для этого ЗУ, или апгрейдить прошивки других ЗУ.
Чтобы не затевать эту котовасию, предлагаю доработать прошивку следующим образом. При вызове `CONTROL_HandleClampActions` сразу опрашивается метка до перехода в машину состояний. Сценарии:
1. Если всё ок, то переходим к машине состояний
2. Если метка прочитана, но не совпадает, то вернуть юзер еррор operation blocked. Указатель на юзер еррор можно передать аргументом в `CONTROL_HandleClampActions`
3. Если метка не читается, то выставить фолт

2023-10-31 07:07 UTC, IvanovDmtr commented on Firmware/Sources/Controller/Controller.c
> +			break;
Не совсем понял, как ты предлагал возвращать UserError через аргумент функции CONTROL_HandleClampActions, когда эта функция вызывается из прерывания по таймеру. Сделал по своему.

2023-11-01 10:12 UTC, asytyi approved these changes

2023-11-01 10:12 UTC, merged